version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
        - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/?authSource=admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
    networks:
      - backend-network

#  cv-backend:
#    image: cv-backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - mongo
#    ports:
#      - "8080:8080"
#    environment:
#      MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/${MONGODB_DB}?authSource=admin
#      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#    networks:
#      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local